export const env = {
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL || "",
  NEXT_PUBLIC_APPWRITE_ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT || "",
  NEXT_PUBLIC_APPWRITE_PROJECT: process.env.NEXT_PUBLIC_APPWRITE_PROJECT || "",
  NEXT_PUBLIC_APPWRITE_DATABASE_ID: process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID || "",
  NEXT_PUBLIC_APPWRITE_PROFILE_COLLECTION_ID: process.env.NEXT_PUBLIC_APPWRITE_PROFILE_COLLECTION_ID || "",
  NEXT_PUBLIC_APPWRITE_POST_COLLECTION_ID: process.env.NEXT_PUBLIC_APPWRITE_POST_COLLECTION_ID || "",
  NEXT_PUBLIC_APPWRITE_LIKE_COLLECTION_ID: process.env.NEXT_PUBLIC_APPWRITE_LIKE_COLLECTION_ID || "",
  NEXT_PUBLIC_APPWRITE_COMMENT_COLLECTION_ID: process.env.NEXT_PUBLIC_APPWRITE_COMMENT_COLLECTION_ID || "",
  NEXT_PUBLIC_APPWRITE_STORAGE_BUCKET_ID: process.env.NEXT_PUBLIC_APPWRITE_STORAGE_BUCKET_ID || "",
};

export function envReady(): boolean {
  return (
    !!env.NEXT_PUBLIC_APPWRITE_ENDPOINT &&
    !!env.NEXT_PUBLIC_APPWRITE_PROJECT &&
    !!env.NEXT_PUBLIC_APPWRITE_DATABASE_ID &&
    !!env.NEXT_PUBLIC_APPWRITE_PROFILE_COLLECTION_ID &&
    !!env.NEXT_PUBLIC_APPWRITE_POST_COLLECTION_ID &&
    !!env.NEXT_PUBLIC_APPWRITE_LIKE_COLLECTION_ID &&
    !!env.NEXT_PUBLIC_APPWRITE_COMMENT_COLLECTION_ID &&
    !!env.NEXT_PUBLIC_APPWRITE_STORAGE_BUCKET_ID
  );
}

